empresa/urls.py
from django.urls import path
from . import views

app_name = 'empresa'

urlpatterns = [
    path('', views.ecv_list, name='ecv_list'),
    path('<slug:category_slug>/', views.ecv_list, name='ecv_list_by_category'),
    path('<int:id>/<slug:slug>/', views.ecv_detail, name='ecv_detail'),
]

loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('empresa.urls', namespace='empresa')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

empresa/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('empresa:ecv_list_by_category',
                       args=[self.slug])

class Ecv(models.Model):
    category = models.ForeignKey(Category,
                                  related_name='categorias',
                                  on_delete=models.CASCADE)



    slug = models.CharField(max_length=200, unique=True)
    name = models.CharField(max_length=200, db_index=True)
    endereco = models.CharField(max_length=300, db_index=True)
    email = models.CharField(max_length=200, db_index=True)
    link =models.CharField(max_length=300, db_index=True)
    telefone = models.CharField(max_length=200, db_index=True)


    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together =(('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('empresa:ecv_detail',
                       args=[self.id, self.slug])

empresa/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Ecv


def ecv_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    ecvs = Ecv.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        ecvs = ecvs.filter(category=category)
    return render(request,
                  'empresa/ecv/list.html',
                  {'category': category,
                   'categories': categories,
                   'ecvs': ecvs})


def ecv_detail(request, id, slug):
    ecv = get_object_or_404(Livro,
                                id=id,
                                slug=slug,
                                available=True)

    return render(request,
                  'empresa/ecv/detail.html',
                  {'ecv': ecv})

estoque/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Livro


def livro_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    livros = Livro.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        livros = livros.filter(category=category)
    return render(request,
                  'estoque/livro/list.html',
                  {'category': category,
                   'categories': categories,
                   'livros': livros})


def livro_detail(request, id, slug):
    livro = get_object_or_404(Livro,
                                id=id,
                                slug=slug,
                                available=True)

    return render(request,
                  'estoque/livro/detail.html',
                  {'livro': livro})

empresa/templates/empresa/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}My Loja{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">Site Detran</a>
    </div>
    <div id="subheader">
      <div class="livros">
             <h2>Empresas Credenciadas de Vistorias de Veículos<h2>
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

empresa/templates/empresa/ecv/detail.html
{% extends "emprsa/base.html" %}
{% load static %}

{% block title %}
  {{ ecv.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
        <h1>{{ ecv.name }}</h1>




  </div>
{% endblock %}

empresa/templates/empresa/ecv/list.html
{% extends "empresa/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Empresas - ECV´s{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Buscar por Cidades</h3>
    <ul>
      <li {% if not actegory %}class="selected"{% endif %}>
        <a href="{% url "empresa:ecv_list" %}">Todas</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Todas{% endif %}</h1>
    {% for ecv in ecvs %}
      <div class="item">
        <a href="{{ ecv.get_absolute_url }}">

        </a>
        <!--  <a href="{{ ecv.get_absolute_url }}">{{ ecv.name }}</a> -->
        Empresa : {{ ecv.name }}
        Endereço : {{ ecv.endereco }}
        E-mail : {{ ecv.email }}
        Link :{{ecv.link}}
        Telefone :{{ecv.telefone}}



        <br>

      </div>
    {% endfor %}
  </div>
{% endblock %}

estoque/templates/estoque/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}My Loja{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">My Loja</a>
    </div>
    <div id="subheader">
      <div class="livros">
             Listas de Livros
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>